### PR TITLE
fix breaking change due to google's response format

### PR DESCRIPTION
**Pull request by ellisbrown**

### CODE REVIEW

**Comment by mrclean789** [comment]
Looks like its broken again 😮‍💨

**Comment by ellisbrown** [comment]
> Looks like its broken again 😮‍💨

@mrclean789 I think they released a change Friday which broke things for us, rolled it back on Monday, and then just re-released. I just un-did my revert from Monday and things are working 👍

**Comment by Joeclinton1** [comment]
Tested it and it works! Will merge now.

**Comment by Joeclinton1** [comment]
Btw, the change to the test file should've been in a separate commit, but I've already merged it and it's not a big deal.

**Comment by rotaugenlaubfrosch** [comment]
Wow, this is insane! Thank you for fixing it so quickly - it works fine again👍🏻

**Comment by alifadill** [comment]
object['image_link'], object['image_format'], main_directory, dir_name, count,
    ~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

OR sometimes like this:
Expecting value: line 1 column 1 (char 0)
Image objects data unpacking failed.

**Comment by pqpq17** [comment]
@alifadill same problem, have you solved it?

**Comment by slott** [comment]
Just tried this repo and got an error with a message saying to report it here:


Item no.: 1 --> Item name = cats
Evaluating...
Expecting value: line 1 column 1 (char 0)
Image objects data unpacking failed. Please leave a comment with the above error at https://github.com/Joeclinton1/google-images-download/pull/26

**Pull request merged**
